# Generated by Django 5.2.7 on 2025-11-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditApp', '0002_alter_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='parent',
        ),
    ]
